#include "predefined.h"

Language Predefined::Afrikaans;
Language Predefined::Albanian;
Language Predefined::Amharic;
Language Predefined::Arabic;
Language Predefined::Armenian;
Language Predefined::Assamese;
Language Predefined::Aymara;
Language Predefined::Azerbaijani;
Language Predefined::Bambara;
Language Predefined::Bashkir;
Language Predefined::Basque;
Language Predefined::Belarusian;
Language Predefined::Bengali;
Language Predefined::Bhojpuri;
Language Predefined::Bosnian;
Language Predefined::Bulgarian;
Language Predefined::Cantonese;
Language Predefined::Catalan;
Language Predefined::Cebuano;
Language Predefined::Chichewa;
Language Predefined::Chinese;
Language Predefined::ChineseLiterary;
Language Predefined::ChineseSimplified;
Language Predefined::ChineseTraditional;
Language Predefined::ChineseSimplifiedHANS;
Language Predefined::ChineseTraditionalHANT;
Language Predefined::Chuvash;
Language Predefined::Corsican;
Language Predefined::Croatian;
Language Predefined::Czech;
Language Predefined::Danish;
Language Predefined::Dari;
Language Predefined::Dhivehi;
Language Predefined::Dogri;
Language Predefined::Dutch;
Language Predefined::EasternMari;
Language Predefined::English;
Language Predefined::EnglishUS;
Language Predefined::EnglishGB;
Language Predefined::Esperanto;
Language Predefined::Estonian;
Language Predefined::Ewe;
Language Predefined::Faroese;
Language Predefined::Fijian;
Language Predefined::Filipino;
Language Predefined::Finnish;
Language Predefined::French;
Language Predefined::FrenchCanadian;
Language Predefined::Frisian;
Language Predefined::Galician;
Language Predefined::Georgian;
Language Predefined::German;
Language Predefined::Greek;
Language Predefined::Guarani;
Language Predefined::Gujarati;
Language Predefined::HaitianCreole;
Language Predefined::Hausa;
Language Predefined::Hawaiian;
Language Predefined::Hebrew;
Language Predefined::HillMari;
Language Predefined::Hindi;
Language Predefined::Hmong;
Language Predefined::Hungarian;
Language Predefined::Icelandic;
Language Predefined::Igbo;
Language Predefined::Ilocano;
Language Predefined::Indonesian;
Language Predefined::Inuinnaqtun;
Language Predefined::Inuktitut;
Language Predefined::InuktitutLatin;
Language Predefined::Irish;
Language Predefined::Italian;
Language Predefined::Japanese;
Language Predefined::Javanese;
Language Predefined::Kannada;
Language Predefined::Kazakh;
Language Predefined::Khmer;
Language Predefined::Kinyarwanda;
Language Predefined::Klingon;
Language Predefined::Konkani;
Language Predefined::Korean;
Language Predefined::Krio;
Language Predefined::KurdishCentral;
Language Predefined::KurdishNorthern;
Language Predefined::Kyrgyz;
Language Predefined::Lao;
Language Predefined::Latin;
Language Predefined::Latvian;
Language Predefined::Lingala;
Language Predefined::Lithuanian;
Language Predefined::Luganda;
Language Predefined::Luxembourgish;
Language Predefined::Macedonian;
Language Predefined::Maithili;
Language Predefined::Malagasy;
Language Predefined::Malay;
Language Predefined::Malayalam;
Language Predefined::Maltese;
Language Predefined::Maori;
Language Predefined::Marathi;
Language Predefined::Meiteilon;
Language Predefined::Mizo;
Language Predefined::Mongolian;
Language Predefined::MongolianTraditional;
Language Predefined::Myanmar;
Language Predefined::Nepali;
Language Predefined::Norwegian;
Language Predefined::NorwegianNB;
Language Predefined::Odia;
Language Predefined::Oromo;
Language Predefined::Papiamento;
Language Predefined::Pashto;
Language Predefined::Persian;
Language Predefined::Polish;
Language Predefined::Portuguese;
Language Predefined::PortugueseBrazilian;
Language Predefined::PortugueseEuropean;
Language Predefined::Punjabi;
Language Predefined::Quechua;
Language Predefined::QuerétaroOtomi;
Language Predefined::Romanian;
Language Predefined::Russian;
Language Predefined::Samoan;
Language Predefined::Sanskrit;
Language Predefined::ScotsGaelic;
Language Predefined::Sepedi;
Language Predefined::SerbianCyrillic;
Language Predefined::SerbianLatin;
Language Predefined::Sesotho;
Language Predefined::Shona;
Language Predefined::Sindhi;
Language Predefined::Sinhala;
Language Predefined::Slovak;
Language Predefined::Slovenian;
Language Predefined::Somali;
Language Predefined::Spanish;
Language Predefined::SpanishLatinAmerican;
Language Predefined::Sundanese;
Language Predefined::Swahili;
Language Predefined::Swedish;
Language Predefined::Tahitian;
Language Predefined::Tajik;
Language Predefined::Tamil;
Language Predefined::Tatar;
Language Predefined::Telugu;
Language Predefined::Thai;
Language Predefined::Tibetan;
Language Predefined::Tigrinya;
Language Predefined::Tongan;
Language Predefined::Tsonga;
Language Predefined::Turkish;
Language Predefined::Turkmen;
Language Predefined::Twi;
Language Predefined::Udmurt;
Language Predefined::Ukrainian;
Language Predefined::UpperSorbian;
Language Predefined::Urdu;
Language Predefined::Uyghur;
Language Predefined::Uzbek;
Language Predefined::Vietnamese;
Language Predefined::Welsh;
Language Predefined::Xhosa;
Language Predefined::Yakut;
Language Predefined::Yiddish;
Language Predefined::Yoruba;
Language Predefined::YucatecMaya;
Language Predefined::Zulu;

void Predefined::init() {
    Afrikaans = Language(QStringLiteral("af"), QStringLiteral("Afrikaans"));
    Albanian = Language(QStringLiteral("sq"), QStringLiteral("Albanian"));
    Amharic = Language(QStringLiteral("am"), QStringLiteral("Amharic"));
    Arabic = Language(QStringLiteral("ar"), QStringLiteral("Arabic"));
    Armenian = Language(QStringLiteral("hy"), QStringLiteral("Armenian"));
    Assamese = Language(QStringLiteral("as"), QStringLiteral("Assamese"));
    Aymara = Language(QStringLiteral("ay"), QStringLiteral("Aymara"));
    Azerbaijani = Language(QStringLiteral("az"), QStringLiteral("Azerbaijani"));
    Bambara = Language(QStringLiteral("bm"), QStringLiteral("Bambara"));
    Bashkir = Language(QStringLiteral("ba"), QStringLiteral("Bashkir"));
    Basque = Language(QStringLiteral("eu"), QStringLiteral("Basque"));
    Belarusian = Language(QStringLiteral("be"), QStringLiteral("Belarusian"));
    Bengali = Language(QStringLiteral("bn"), QStringLiteral("Bengali"));
    Bhojpuri = Language(QStringLiteral("bho"), QStringLiteral("Bhojpuri"));
    Bosnian = Language(QStringLiteral("bs"), QStringLiteral("Bosnian"));
    Bulgarian = Language(QStringLiteral("bg"), QStringLiteral("Bulgarian"));
    Cantonese = Language(QStringLiteral("yue"), QStringLiteral("Cantonese"));
    Catalan = Language(QStringLiteral("ca"), QStringLiteral("Catalan"));
    Cebuano = Language(QStringLiteral("ceb"), QStringLiteral("Cebuano"));
    Chichewa = Language(QStringLiteral("ny"), QStringLiteral("Chichewa"));

    Chinese = Language(QStringLiteral("zh"), QStringLiteral("Chinese"));
    ChineseLiterary = Language(QStringLiteral("lzh"), QStringLiteral("Chinese Literary"));
    ChineseSimplified = Language(QStringLiteral("zh-cn"), QStringLiteral("Chinese Simplified"));
    ChineseTraditional = Language(QStringLiteral("zh-tw"), QStringLiteral("Chinese Traditional"));
    ChineseSimplifiedHANS = Language(QStringLiteral("zh-hans"), QStringLiteral("Chinese Simplified"));
    ChineseTraditionalHANT = Language(QStringLiteral("zh-hant"), QStringLiteral("Chinese Traditional"));

    Chuvash = Language(QStringLiteral("cv"), QStringLiteral("Chuvash"));
    Corsican = Language(QStringLiteral("co"), QStringLiteral("Corsican"));
    Croatian = Language(QStringLiteral("hr"), QStringLiteral("Croatian"));
    Czech = Language(QStringLiteral("cs"), QStringLiteral("Czech"));
    Danish = Language(QStringLiteral("da"), QStringLiteral("Danish"));
    Dari = Language(QStringLiteral("prs"), QStringLiteral("Dari"));
    Dhivehi = Language(QStringLiteral("dv"), QStringLiteral("Dhivehi"));
    Dogri = Language(QStringLiteral("doi"), QStringLiteral("Dogri"));
    Dutch = Language(QStringLiteral("nl"), QStringLiteral("Dutch"));
    EasternMari = Language(QStringLiteral("mhr"), QStringLiteral("Eastern Mari"));

    English = Language(QStringLiteral("en"), QStringLiteral("English"));
    EnglishUS = Language(QStringLiteral("en-us"), QStringLiteral("English United States"));
    EnglishGB = Language(QStringLiteral("en-gb"), QStringLiteral("English United Kingdom"));

    Esperanto = Language(QStringLiteral("eo"), QStringLiteral("Esperanto"));
    Estonian = Language(QStringLiteral("et"), QStringLiteral("Estonian"));
    Ewe = Language(QStringLiteral("ee"), QStringLiteral("Ewe"));
    Faroese = Language(QStringLiteral("fo"), QStringLiteral("Faroese"));
    Fijian = Language(QStringLiteral("fj"), QStringLiteral("Fijian"));
    Filipino = Language(QStringLiteral("tl"), QStringLiteral("Filipino"));
    Finnish = Language(QStringLiteral("fi"), QStringLiteral("Finnish"));
    French = Language(QStringLiteral("fr"), QStringLiteral("French"));
    FrenchCanadian = Language(QStringLiteral("fr-ca"), QStringLiteral("French Canadian"));
    Frisian = Language(QStringLiteral("fy"), QStringLiteral("Frisian"));
    Galician = Language(QStringLiteral("gl"), QStringLiteral("Galician"));
    Georgian = Language(QStringLiteral("ka"), QStringLiteral("Georgian"));
    German = Language(QStringLiteral("de"), QStringLiteral("German"));
    Greek = Language(QStringLiteral("el"), QStringLiteral("Greek"));
    Guarani = Language(QStringLiteral("gn"), QStringLiteral("Guarani"));
    Gujarati = Language(QStringLiteral("gu"), QStringLiteral("Gujarati"));
    HaitianCreole = Language(QStringLiteral("ht"), QStringLiteral("Haitian Creole"));
    Hausa = Language(QStringLiteral("ha"), QStringLiteral("Hausa"));
    Hawaiian = Language(QStringLiteral("haw"), QStringLiteral("Hawaiian"));
    Hebrew = Language(QStringLiteral("he"), QStringLiteral("Hebrew"));
    HillMari = Language(QStringLiteral("mrj"), QStringLiteral("Hill Mari"));
    Hindi = Language(QStringLiteral("hi"), QStringLiteral("Hindi"));
    Hmong = Language(QStringLiteral("hmn"), QStringLiteral("Hmong"));
    Hungarian = Language(QStringLiteral("hu"), QStringLiteral("Hungarian"));
    Icelandic = Language(QStringLiteral("is"), QStringLiteral("Icelandic"));
    Igbo = Language(QStringLiteral("ig"), QStringLiteral("Igbo"));
    Ilocano = Language(QStringLiteral("ilo"), QStringLiteral("Ilocano"));
    Indonesian = Language(QStringLiteral("id"), QStringLiteral("Indonesian"));
    Inuinnaqtun = Language(QStringLiteral("ikt"), QStringLiteral("Inuinnaqtun"));
    Inuktitut = Language(QStringLiteral("iu"), QStringLiteral("Inuktitut"));
    InuktitutLatin = Language(QStringLiteral("iu-latn"), QStringLiteral("Inuktitut Latin"));
    Irish = Language(QStringLiteral("ga"), QStringLiteral("Irish"));
    Italian = Language(QStringLiteral("it"), QStringLiteral("Italian"));
    Japanese = Language(QStringLiteral("ja"), QStringLiteral("Japanese"));
    Javanese = Language(QStringLiteral("jv"), QStringLiteral("Javanese"));
    Kannada = Language(QStringLiteral("kn"), QStringLiteral("Kannada"));
    Kazakh = Language(QStringLiteral("kk"), QStringLiteral("Kazakh"));
    Khmer = Language(QStringLiteral("km"), QStringLiteral("Khmer"));
    Kinyarwanda = Language(QStringLiteral("rw"), QStringLiteral("Kinyarwanda"));
    Klingon = Language(QStringLiteral("tlh-latn"), QStringLiteral("Klingon"));
    Konkani = Language(QStringLiteral("gom"), QStringLiteral("Konkani"));
    Korean = Language(QStringLiteral("ko"), QStringLiteral("Korean"));
    Krio = Language(QStringLiteral("kri"), QStringLiteral("Krio"));
    KurdishCentral = Language(QStringLiteral("ckb"), QStringLiteral("Kurdish Central"));
    KurdishNorthern = Language(QStringLiteral("ku"), QStringLiteral("Kurdish Northern"));
    Kyrgyz = Language(QStringLiteral("ky"), QStringLiteral("Kyrgyz"));
    Lao = Language(QStringLiteral("lo"), QStringLiteral("Lao"));
    Latin = Language(QStringLiteral("la"), QStringLiteral("Latin"));
    Latvian = Language(QStringLiteral("lv"), QStringLiteral("Latvian"));
    Lingala = Language(QStringLiteral("ln"), QStringLiteral("Lingala"));
    Lithuanian = Language(QStringLiteral("lt"), QStringLiteral("Lithuanian"));
    Luganda = Language(QStringLiteral("lg"), QStringLiteral("Luganda"));
    Luxembourgish = Language(QStringLiteral("lb"), QStringLiteral("Luxembourgish"));
    Macedonian = Language(QStringLiteral("mk"), QStringLiteral("Macedonian"));
    Maithili = Language(QStringLiteral("mai"), QStringLiteral("Maithili"));
    Malagasy = Language(QStringLiteral("mg"), QStringLiteral("Malagasy"));

    Malay = Language(QStringLiteral("ms"), QStringLiteral("Malay"));
    Malayalam = Language(QStringLiteral("ml"), QStringLiteral("Malayalam"));
    Maltese = Language(QStringLiteral("mt"), QStringLiteral("Maltese"));
    Maori = Language(QStringLiteral("mi"), QStringLiteral("Maori"));
    Marathi = Language(QStringLiteral("mr"), QStringLiteral("Marathi"));
    Meiteilon = Language(QStringLiteral("mni-mtei"), QStringLiteral("Meiteilon"));
    Mizo = Language(QStringLiteral("lus"), QStringLiteral("Mizo"));
    Mongolian = Language(QStringLiteral("mn"), QStringLiteral("Mongolian"));
    MongolianTraditional = Language(QStringLiteral("mn-mong"), QStringLiteral("Mongolian Traditional"));
    Myanmar = Language(QStringLiteral("my"), QStringLiteral("Myanmar"));
    Nepali = Language(QStringLiteral("ne"), QStringLiteral("Nepali"));

    Norwegian = Language(QStringLiteral("no"), QStringLiteral("Norwegian"));
    NorwegianNB = Language(QStringLiteral("nb"), QStringLiteral("Norwegian"));

    Odia = Language(QStringLiteral("or"), QStringLiteral("Odia"));
    Oromo = Language(QStringLiteral("om"), QStringLiteral("Oromo"));
    Papiamento = Language(QStringLiteral("pap"), QStringLiteral("Papiamento"));
    Pashto = Language(QStringLiteral("ps"), QStringLiteral("Pashto"));
    Persian = Language(QStringLiteral("fa"), QStringLiteral("Persian"));
    Polish = Language(QStringLiteral("pl"), QStringLiteral("Polish"));

    Portuguese = Language(QStringLiteral("pt"), QStringLiteral("Portuguese"));
    PortugueseBrazilian = Language(QStringLiteral("pt-br"), QStringLiteral("Portuguese Brazilian"));
    PortugueseEuropean = Language(QStringLiteral("pt-pt"), QStringLiteral("Portuguese European"));

    Punjabi = Language(QStringLiteral("pa"), QStringLiteral("Punjabi"));
    Quechua = Language(QStringLiteral("qu"), QStringLiteral("Quechua"));
    QuerétaroOtomi = Language(QStringLiteral("otq"), QStringLiteral("Querétaro Otomi"));
    Romanian = Language(QStringLiteral("ro"), QStringLiteral("Romanian"));
    Russian = Language(QStringLiteral("ru"), QStringLiteral("Russian"));
    Samoan = Language(QStringLiteral("sm"), QStringLiteral("Samoan"));
    Sanskrit = Language(QStringLiteral("sa"), QStringLiteral("Sanskrit"));
    ScotsGaelic = Language(QStringLiteral("gd"), QStringLiteral("Scots Gaelic"));
    Sepedi = Language(QStringLiteral("nso"), QStringLiteral("Sepedi"));
    SerbianCyrillic = Language(QStringLiteral("sr-cyrl"), QStringLiteral("Serbian Cyrillic"));
    SerbianLatin = Language(QStringLiteral("sr-latn"), QStringLiteral("Serbian Latin"));
    Sesotho = Language(QStringLiteral("st"), QStringLiteral("Sesotho"));
    Shona = Language(QStringLiteral("sn"), QStringLiteral("Shona"));
    Sindhi = Language(QStringLiteral("sd"), QStringLiteral("Sindhi"));
    Sinhala = Language(QStringLiteral("si"), QStringLiteral("Sinhala"));
    Slovak = Language(QStringLiteral("sk"), QStringLiteral("Slovak"));
    Slovenian = Language(QStringLiteral("sl"), QStringLiteral("Slovenian"));
    Somali = Language(QStringLiteral("so"), QStringLiteral("Somali"));

    Spanish = Language(QStringLiteral("es"), QStringLiteral("Spanish"));
    SpanishLatinAmerican = Language(QStringLiteral("es-419"), QStringLiteral("Spanish Latin American"));

    Sundanese = Language(QStringLiteral("su"), QStringLiteral("Sundanese"));
    Swahili = Language(QStringLiteral("sw"), QStringLiteral("Swahili"));
    Swedish = Language(QStringLiteral("sv"), QStringLiteral("Swedish"));
    Tahitian = Language(QStringLiteral("ty"), QStringLiteral("Tahitian"));
    Tajik = Language(QStringLiteral("tg"), QStringLiteral("Tajik"));
    Tamil = Language(QStringLiteral("ta"), QStringLiteral("Tamil"));
    Tatar = Language(QStringLiteral("tt"), QStringLiteral("Tatar"));
    Telugu = Language(QStringLiteral("te"), QStringLiteral("Telugu"));
    Thai = Language(QStringLiteral("th"), QStringLiteral("Thai"));
    Tibetan = Language(QStringLiteral("bo"), QStringLiteral("Tibetan"));
    Tigrinya = Language(QStringLiteral("ti"), QStringLiteral("Tigrinya"));
    Tongan = Language(QStringLiteral("to"), QStringLiteral("Tongan"));
    Tsonga = Language(QStringLiteral("ts"), QStringLiteral("Tsonga"));
    Turkish = Language(QStringLiteral("tr"), QStringLiteral("Turkish"));
    Turkmen = Language(QStringLiteral("tk"), QStringLiteral("Turkmen"));
    Twi = Language(QStringLiteral("tw"), QStringLiteral("Twi"));
    Udmurt = Language(QStringLiteral("udm"), QStringLiteral("Udmurt"));
    Ukrainian = Language(QStringLiteral("uk"), QStringLiteral("Ukrainian"));
    UpperSorbian = Language(QStringLiteral("hsb"), QStringLiteral("Upper Sorbian"));
    Urdu = Language(QStringLiteral("ur"), QStringLiteral("Urdu"));
    Uyghur = Language(QStringLiteral("ug"), QStringLiteral("Uyghur"));
    Uzbek = Language(QStringLiteral("uz"), QStringLiteral("Uzbek"));
    Vietnamese = Language(QStringLiteral("vi"), QStringLiteral("Vietnamese"));
    Welsh = Language(QStringLiteral("cy"), QStringLiteral("Welsh"));
    Xhosa = Language(QStringLiteral("xh"), QStringLiteral("Xhosa"));
    Yakut = Language(QStringLiteral("sah"), QStringLiteral("Yakut"));
    Yiddish = Language(QStringLiteral("yi"), QStringLiteral("Yiddish"));
    Yoruba = Language(QStringLiteral("yo"), QStringLiteral("Yoruba"));
    YucatecMaya = Language(QStringLiteral("yua"), QStringLiteral("Yucatec Maya"));
    Zulu = Language(QStringLiteral("zu"), QStringLiteral("Zulu"));
}
